---
- name: Register VM_IP Artifact
  hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:
  - name: Save host data within a Group
    add_host:
      hostname: "{{ vm_ip }}"
      groupname: rhsm_servers

  - name: Wait for SSH to come up
    wait_for: host={{ vm_ip }} port=22 delay=10 timeout=60

- name: Unregister RHEL node from RHSM
  hosts: rhsm_servers
  tasks:
  - name: Unregister RHEL from Subscription Manager
    redhat_subscription:
      state: absent
      username: "{{ rhsm_username }}"
      password: "{{ rhsm_password }}"
    when: ansible_os_family == "RedHat"
